# Generated by Django 4.0.1 on 2022-01-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agregat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregat', models.CharField(max_length=50, verbose_name='Прибор')),
                ('date', models.DateField(verbose_name='Дата изготовления')),
                ('update', models.DateField(verbose_name='Дата ремонта')),
            ],
        ),
    ]
