# Generated by Django 4.0.1 on 2022-01-21 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vertolet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vs_number', models.CharField(max_length=20, verbose_name='Вертолет')),
            ],
            options={
                'verbose_name': 'Вертолет',
                'verbose_name_plural': 'Вертолеты',
            },
        ),
        migrations.AlterModelOptions(
            name='agregat',
            options={'verbose_name': 'Прибор', 'verbose_name_plural': 'Приборы'},
        ),
        migrations.AddField(
            model_name='agregat',
            name='vertolet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.vertolet'),
        ),
    ]
