# Generated by Django 4.0.1 on 2022-01-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_vertolet_alter_agregat_options_agregat_vertolet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertolet',
            name='vs_number',
            field=models.CharField(max_length=20, verbose_name='Номер ВС'),
        ),
    ]
